apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: kutt
  name: kutt
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: kutt
  template:
    metadata:
      labels:
        app.kubernetes.io/name: kutt
    spec:
      containers:
        - name: kutt
          image: kutt/kutt:v2.7.4
          envFrom:
            - configMapRef:
                name: config
          env:
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: postgresql
                  key: host
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: postgresql
                  key: port
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: postgresql
                  key: db
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: postgresql
                  key: user
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgresql
                  key: password
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: jwt
                  key: token
            - name: REDIS_HOST
              valueFrom:
                secretKeyRef:
                  name: redis
                  key: address
            - name: REDIS_PORT
              valueFrom:
                secretKeyRef:
                  name: redis
                  key: port
          startupProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 30
          readinessProbe:
            httpGet:
              path: /health
              port: http
          livenessProbe:
            httpGet:
              path: /health
              port: http
          ports:
            - containerPort: 3000
              name: http
          resources:
            limits:
              cpu: "666"
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 512Mi
