apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: certificate
spec:
  secretStoreRef:
    name: parameter-store
    kind: ClusterSecretStore
  refreshInterval: 1m
  target:
    name: redis
    creationPolicy: Owner
    deletionPolicy: Delete
  data:
    - secretKey: certificate_arn
      remoteRef:
        key: ${cluster_name}-kutt-certificate-arn
