apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: postgresql
spec:
  secretStoreRef:
    name: secrets-manager
    kind: ClusterSecretStore
  refreshInterval: 1m
  target:
    name: postgresql
    creationPolicy: Owner
    deletionPolicy: Delete
  data:
    - secretKey: db
      remoteRef:
        key: ${cluster_name}-postgresql
        property: dbname
    - secretKey: host
      remoteRef:
        key: ${cluster_name}-postgresql
        property: host
    - secretKey: password
      remoteRef:
        key: ${cluster_name}-postgresql
        property: password
    - secretKey: port
      remoteRef:
        key: ${cluster_name}-postgresql
        property: port
    - secretKey: user
      remoteRef:
        key: ${cluster_name}-postgresql
        property: username
