apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: jwt
spec:
  secretStoreRef:
    name: secrets-manager
    kind: ClusterSecretStore
  refreshInterval: 1m
  target:
    name: jwt
    creationPolicy: Owner
    deletionPolicy: Delete
  data:
    - secretKey: token
      remoteRef:
        key: ${cluster_name}-kutt-jwt
