apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: redis
spec:
  secretStoreRef:
    name: parameter-store
    kind: ClusterSecretStore
  refreshInterval: 1m
  target:
    name: redis
    creationPolicy: Owner
    deletionPolicy: Delete
  data:
    - secretKey: address
      remoteRef:
        key: ${cluster_name}-redis-cluster-address
    - secretKey: port
      remoteRef:
        key: ${cluster_name}-redis-cluster-port
