apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kutt
resources:
  - namespace.yaml
  - deployment.yaml
  - externalsecret-jwt.yaml
  - externalsecret-postgresql.yaml
  - externalsecret-redis.yaml
  - ingress.yaml
  - service.yaml
configMapGenerator:
  - name: config
    envs:
      - files/config.env
