apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: external-secrets-stores
  namespace: flux-system
spec:
  dependsOn:
    - name: external-secrets
  interval: 1m
  sourceRef:
    kind: OCIRepository
    name: flux-system
  path: ./external-secrets-stores
  prune: true
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-vars
