apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system
resources:
  - all.yaml
  - aws-load-balancer-controller.yaml
  - cluster-autoscaler.yaml
  - external-dns.yaml
  - external-secrets.yaml
  - external-secrets-stores.yaml
  - flux-system.yaml
  - kutt.yaml
