apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: kutt
  namespace: flux-system
spec:
  dependsOn:
    - name: aws-load-balancer-controller
    - name: external-secrets-stores
  interval: 1m
  sourceRef:
    kind: OCIRepository
    name: flux-system
  path: ./kutt
  prune: true
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-vars
